### ISSUE TITLE
集成Oppo推送时出错

### ISSUE THREAD

**Issue by mingchaogui** [easemob/im_flutter_sdk#175]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.content.Context.getPackageManager()' on a null object reference
        at com.heytap.mcssdk.d.a(Unknown Source:7)
        at com.heytap.mcssdk.d.l(Unknown Source:6)
        at com.heytap.mcssdk.d.n(Unknown Source:0)
        at com.heytap.msp.push.HeytapPushManager.isSupportPush(Unknown Source:4)
        at com.hyphenate.push.platform.oppo.a.b(Unknown Source:0)
        at com.hyphenate.push.platform.a.a(Unknown Source:6)
        at com.hyphenate.push.EMPushHelper.a(Unknown Source:142)
        at com.hyphenate.push.EMPushHelper.register(Unknown Source:35)
        at com.hyphenate.chat.EMClient$7.run(Unknown Source:204)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

看了下HeytapPushManager源码，也许在调用isSupportPush()之前需要先init()传入context。

**Comment by mingchaogui** [comment]
1)应用必须要调用init(...)接口，才能执行后续操作。

2)由于不是所有平台都支持OPPO PUSH，提供接口HeytapPushManager.isSupportPush()方便应用判断是否支持,支持才能执行后续操作。

3)通过调用HeytapPushManager.register(...)进行应用注册，注册成功后,您可以在ICallBackResultService的onRegister回调方法中得到RegId,您可以将RegId上传到自己的服务器，方便向其发消息。初始化相关参数具体要求参考详细API说明中的初始化部分。

4)为了提高push的注册率，你可以在Application的onCreate中初始化push。你也可以根据需要，在其他地方初始化push。如果第一次注册失败,第二次可以直接调用PushManager.getInstance().getRegister()进行重试,此方法默认会使用第一次传入的参数掉调用注册。

我去查看了官方文档。由于这是Android SDK的问题，找不到反馈途径，麻烦你们转发下。

**Comment by mingchaogui** [comment]
目前可自行在Application#onCreate()添加以下代码解决：

HeytapPushManager.init(this, BuildConfig.DEBUG)

**Comment by apex-wang** [comment]
好的 感谢您的反馈 这个问题是已知问题 我们代码改了还未提交 用户可以先自己在应用层初始化一下 我们后面会更新代码

**Comment by gaoobin** [comment]
问题都没解决怎么就关闭了呢？

**Comment by apex-wang** [comment]
问题没解决？是集成后没收到推送 还是有报错？ 看你提供的异常信息与另一个客户提供的完全一致 而且那个客户加了初始化后应该就没有这个报错了才对，我这边以为已经解决了 实在不好意思  目前是什么现象了？
