### ISSUE TITLE
release时候Failed to handle method call

### ISSUE THREAD

**Issue by panzhoutao** [easemob/im_flutter_sdk#269]
2021-03-30 11:08:24.701 31579-31579/? E/MethodChannel#com.easemob.im/em_client: Failed to handle method call
    e.a.a.a.b: libhyphenate.so
        at e.a.a.a.a.a(Unknown Source:155)
        at e.a.a.a.d.c(Unknown Source:121)
        at e.a.a.a.d.a(Unknown Source:21)
        at e.a.a.a.c.a(Unknown Source:5)
        at e.a.a.a.c.a(Unknown Source:1)
        at d.f.m.f.y(Unknown Source:13)
        at d.f.m.f.a(Unknown Source:30)
        at d.c.a.s2.f(Unknown Source:20)
        at d.c.a.s2.onMethodCall(Unknown Source:48)
        at f.a.d.a.j$a.a(Unknown Source:17)
        at io.flutter.embedding.engine.e.b.a(Unknown Source:57)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:181)
        at android.app.ActivityThread.main(ActivityThread.java:7562)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by apex-wang** [comment]
这边打包的时候 有添加环信的混淆规则吗？

**Comment by panzhoutao** [comment]
> 这边打包的时候 有添加环信的混淆规则吗？

添加了，也没用
