### ISSUE TITLE
flutter build apk

### ISSUE THREAD

**Issue by CharlesZqikai** [easemob/im_flutter_sdk#336]

**Comment by CharlesZqikai** [comment]
Exception in thread "main" java.io.FileNotFoundException: \Users\dujiepeng\dev\gradle-6.8.3-all.zip (系统找不到指定的路径。)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
        at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
        at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:184)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
        at org.gradle.wrapper.Download.download(Download.java:44)
        at org.gradle.wrapper.Install$1.call(Install.java:61)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)


The plugin ease_call_kit could not be built due to the issue above.

**Comment by anshulkhilrani** [comment]
Have you requested for the WRITE_EXTERNAL_STORAGE permission, because I faced the same issue and it was solved after asking for the permission to do so.

**Comment by dujiepeng** [comment]
您好，这个是指向了本地的gradle，可以在gradle-wrapper.properties里修改成您本地的或者是指向distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all
