### ISSUE TITLE
安卓SDK 3.8.3升级 提示libsqlite.so找不到文件

### ISSUE THREAD

**Issue by SuperCarGT** [easemob/im_flutter_sdk#372]
> [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.UnsatisfiedLinkError: dlopen failed: library "libsqlite.so" not found
        at java.lang.Runtime.load0(Runtime.java:938)
        at java.lang.System.load(System.java:1632)
        at internal.com.getkeepsafe.relinker.SystemLibraryLoader.loadPath(Unknown Source:0)
        at internal.com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(Unknown Source:182)
        at internal.com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(Unknown Source:21)
        at internal.com.getkeepsafe.relinker.ReLinker.loadLibrary(Unknown Source:5)
        at internal.com.getkeepsafe.relinker.ReLinker.loadLibrary(Unknown Source:1)
        at com.hyphenate.chat.EMClient.loadLibrary(Unknown Source:13)
        at com.hyphenate.chat.EMClient.init(Unknown Source:32)
        at com.easemob.im_flutter_sdk.EMClientWrapper.init(EMClientWrapper.java:261)
        at com.easemob.im_flutter_sdk.EMClientWrapper.onMethodCall(EMClientWrapper.java:42)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:363)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

**Comment by SuperCarGT** [comment]
已解决
