### ISSUE TITLE
 Unhandled Exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by xiayanping** [easemob/im_flutter_sdk#405]
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
Debug service listening on ws://127.0.0.1:8880/igzuUK6Lk4A=/ws
Syncing files to device Android SDK built for x86...
E/flutter ( 5916): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 5916): #0      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:142:86)
E/flutter ( 5916): #1      MethodChannel.setMethodCallHandler (package:flutter/src/services/platform_channel.dart:378:5)
E/flutter ( 5916): #2      new EMChatManager (package:im_flutter_sdk/src/em_chat_manager.dart:16:14)
E/flutter ( 5916): #3      new EMClient._internal (package:im_flutter_sdk/src/em_client.dart:23:38)
E/flutter ( 5916): #4      EMClient.getInstance (package:im_flutter_sdk/src/em_client.dart:58:41)
E/flutter ( 5916): #5      main (package:ruanyitong_chat/main.dart:13:12)
E/flutter ( 5916): #6      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:142:25)
E/flutter ( 5916): #7      _rootRun (dart:async/zone.dart:1354:13)
E/flutter ( 5916): #8      _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter ( 5916): #9      _runZoned (dart:async/zone.dart:1789:10)
E/flutter ( 5916): #10     runZonedGuarded (dart:async/zone.dart:1777:12)
E/flutter ( 5916): #11     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:138:5)
E/flutter ( 5916): #12     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
E/flutter ( 5916): #13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter ( 5916): 

初始化代码 
EMPushConfig config = EMPushConfig()..enableAPNs('EaseIM_APNS_Product');
  var options = EMOptions(appKey: 'easemob-demo#easeim');
  options.debugModel = true;

  options.pushConfig = config;
  EMClient.getInstance.init(options).then((value) => null);

pubspec.yaml

environment:
  sdk: ">=2.12.0 <3.0.0"

 im_flutter_sdk:
    git:
      url: https://github.com/easemob/im_flutter_sdk.git
      ref: flutter2_dev
  ease_call_kit:
    git:
      url: https://github.com/easemob/ease_call_kit.git
      ref: stable

**Comment by xiayanping** [comment]
少写了一行
WidgetsFlutterBinding.ensureInitialized();

初始化代码
**WidgetsFlutterBinding.ensureInitialized();**
EMPushConfig config = EMPushConfig()..enableAPNs('EaseIM_APNS_Product');
var options = EMOptions(appKey: 'easemob-demo#easeim');
options.debugModel = true;

options.pushConfig = config;
EMClient.getInstance.init(options).then((value) => null);
