### ISSUE TITLE
iOS 下无法编译的问题

### ISSUE THREAD

**Issue by 3442853561** [easemob/im_flutter_sdk#490]
```
Launching lib/main.dart on iPhone 13 Pro Max in debug mode...
Running pod install...                                             953ms
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      A im_flutter_sdk
      - Flutter
      - fluttertoast
      - image_picker
      - shared_preferences_ios
      - webview_flutter_wkwebview

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `fluttertoast` from
    `.symlinks/plugins/fluttertoast/ios`
    -> Fetching podspec for `im_flutter_sdk` from
    `.symlinks/plugins/im_flutter_sdk/ios`
    -> Fetching podspec for `image_picker` from
    `.symlinks/plugins/image_picker/ios`
    -> Fetching podspec for `shared_preferences_ios` from
    `.symlinks/plugins/shared_preferences_ios/ios`
    -> Fetching podspec for `webview_flutter_wkwebview` from
    `.symlinks/plugins/webview_flutter_wkwebview/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local
      because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_5_1_0.txt exists! Returning
      local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/5/1/0/Toast/4.0.0/Toast.podspec.json
      exists! Returning local because checking is only performed in repo update
    [!] CocoaPods could not find compatible versions for pod "im_flutter_sdk":
      In Podfile:
        im_flutter_sdk (from `.symlinks/plugins/im_flutter_sdk/ios`)

    Specs satisfying the `im_flutter_sdk (from
    `.symlinks/plugins/im_flutter_sdk/ios`)` dependency were found, but they
    required a higher minimum deployment target.

    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:31
    7:in `raise_error_unless_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:29
    9:in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:29
    7:in `tap'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:29
    7:in `unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:68
    2:in `attempt_to_activate'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:25
    4:in `process_topmost_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:18
    2:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:i
    n `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/resolver.rb:94:
    in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analy
    zer.rb:1078:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.
    rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analy
    zer.rb:1076:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analy
    zer.rb:124:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:41
    6:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:24
    1:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.
    rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:24
    0:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:16
    1:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command/install
    .rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in
    `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:i
    n `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top
    (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `iOS` with version `9.0` on target
    `Runner` because no platform was specified. Please specify a platform for
    this target in your Podfile. See
    `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone 13 Pro Max.
```

**Comment by 3442853561** [comment]
并且我已经尝试了在 ios 目录下执行 ```pod install --repo-update```

```
Updating local specs repositories
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "im_flutter_sdk":
  In Podfile:
    im_flutter_sdk (from `.symlinks/plugins/im_flutter_sdk/ios`)

Specs satisfying the `im_flutter_sdk (from `.symlinks/plugins/im_flutter_sdk/ios`)` dependency were found, but they required a higher minimum deployment target.

[!] Automatically assigning platform `iOS` with version `9.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
```

**Comment by 3442853561** [comment]
似乎是不支持 iOS 9 导致的 https://github.com/easemob/im_flutter_sdk/issues/179
