### ISSUE TITLE
processGeneralRESTResponseError:: retCode: 408 response: timeout

### ISSUE THREAD

**Issue by ixre** [easemob/im_flutter_sdk#511]
日志见：
```
D/EMChatManager( 1870): convID:177805431209985
W/System.err( 1870): java.net.SocketTimeoutException: timeout
W/System.err( 1870): 	at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:212)
W/System.err( 1870): 	at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:250)
W/System.err( 1870): 	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
W/System.err( 1870): 	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
W/System.err( 1870): 	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
W/System.err( 1870): 	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
W/System.err( 1870): 	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
W/System.err( 1870): 	at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
W/System.err( 1870): 	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
W/System.err( 1870): 	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)
W/System.err( 1870): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
W/System.err( 1870): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
W/System.err( 1870): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
W/System.err( 1870): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
W/System.err( 1870): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(Unknown Source:0)
W/System.err( 1870): 	at com.hyphenate.cloud.HttpClientController.j(Unknown Source:7)
W/System.err( 1870): 	at com.hyphenate.cloud.HttpClientController$HttpParams.getResponse(Unknown Source:9)
W/System.err( 1870): 	at com.hyphenate.cloud.HttpClientManager$Builder.executePrivate(Unknown Source:85)
W/System.err( 1870): 	at com.hyphenate.cloud.HttpClientManager$Builder.executeNormal(Unknown Source:0)
W/System.err( 1870): 	at com.hyphenate.cloud.HttpClientManager$Builder.execute(Unknown Source:13)
W/System.err( 1870): 	at com.hyphenate.cloud.HttpClientManager$Builder.execute(Unknown Source:1)
W/System.err( 1870): 	at com.hyphenate.cloud.HttpClientManager.httpExecute(Unknown Source:38)
W/System.err( 1870): 	at com.hyphenate.cloud.HttpClientManager.httpExecute(Unknown Source:4)
W/System.err( 1870): 	at com.hyphenate.chat.adapter.EMARHttpAPI._httpExecute(Unknown Source:0)
W/System.err( 1870): 	at com.hyphenate.chat.adapter.EMARHttpAPI.httpExecute(Unknown Source:4)
W/System.err( 1870): 	at com.hyphenate.chat.adapter.EMAGroupManager.nativeFetchGroupSpecification(Native Method)
W/System.err( 1870): 	at com.hyphenate.chat.adapter.EMAGroupManager.fetchGroupSpecification(Unknown Source:0)
W/System.err( 1870): 	at com.hyphenate.chat.EMGroupManager.getGroupFromServer(Unknown Source:16)
W/System.err( 1870): 	at com.hyphenate.chat.EMGroupManager$8.run(Unknown Source:4)
W/System.err( 1870): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/System.err( 1870): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/System.err( 1870): 	at java.lang.Thread.run(Thread.java:764)
D/ONE SDK ( 1870): [2022/05/21 13:52:35:709]: [HttpClientManager] error message = timeout
D/ONE SDK ( 1870): [2022/05/21 13:52:35:710]: [HttpClientManager] error execute:timeout
D/ONE SDK ( 1870): [2022/05/21 13:52:35:710]: service url is empty ! 
D/ONE SDK ( 1870): [2022/05/21 13:52:35:711]: fetchMucSpecification:: retCode: 408
D/ONE SDK ( 1870): [2022/05/21 13:52:35:711]: processGeneralRESTResponseError:: retCode: 408 response: timeout
D/ONE SDK ( 1870): [2022/05/21 13:52:35:717]: [callback] onError
I/flutter ( 1870): 2022-05-21 13:52:35.723781 [ bz][ error]: code: 303 desc: Unknown server error
V/MediaPlayer( 1870): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 1870): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer( 1870): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 1870): cleanDrmObj: mDrmObj=null mDrmSessionId=null
D/ONE SDK ( 1870): [2022/05/21 13:52:41:600]: callbackReceievedMessages : shouldCreate : 1
D/ONE SDK ( 1870): [2022/05/21 13:52:41:600]: _EMAChatManagerListenerImpl onReceiveMessage
D/EMChatManager( 1870): convID:177805431209985
D/EMChatManager( 1870): convID:177805431209985
D/ONE SDK ( 1870): [2022/05/21 13:52:41:610]: nativeSearchMessages with keywords
D/EMChatManager( 1870): convID:177805431209985
D/ONE SDK ( 1870): [2022/05/21 13:52:41:618]: nativeSearchMessages with keywords
D/EMChatManager( 1870): convID:177805431209985
D/ONE SDK ( 1870): [2022/05/21 13:52:41:621]: nativeSearchMessages with keywords
D/EMChatManager( 1870): convID:177805431209985
D/ONE SDK ( 1870): [2022/05/21 13:52:41:624]: nativeSearchMessages with keywords
D/EMChatManager( 1870): convID:177805431209985
D/EMChatManager( 1870): convID:177805431209985
D/ONE SDK ( 1870): [2022/05/21 13:52:41:630]: nativeSearchMessages with keywords
D/ONE SDK ( 1870): [2022/05/21 13:52:41:630]: nativeSearchMessages with keywords
D/EMChatManager( 1870): convID:177805431209985
D/ONE SDK ( 1870): [2022/05/21 13:52:41:633]: nativeSearchMessages with keywords
D/ONE SDK ( 1870): [2022/05/21 13:52:41:638]: callbackReceievedMessages : shouldCreate : 1
D/ONE SDK ( 1870): [2022/05/21 13:52:41:638]: _EMAChatManagerListenerImpl onReceiveMessage
```

**Comment by ixre** [comment]
用户出现301 desc: Server response timeout

**Comment by dujiepeng** [comment]
@ixre  这个是什么时候出现的。

**Comment by ixre** [comment]
到现在还有这个问题，但是是个别网络才会这样
