### ISSUE TITLE
登录提示null引用

### ISSUE THREAD

**Issue by ixre** [easemob/im_flutter_sdk#527]
```
/MethodChannel#com.chat.im/chat_client(12501): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.hyphenate.chat.core.EMChatConfigPrivate.l()' on a null object reference
E/MethodChannel#com.chat.im/chat_client(12501): 	at com.hyphenate.chat.EMClient.login(Unknown Source:24)
E/MethodChannel#com.chat.im/chat_client(12501): 	at com.easemob.im_flutter_sdk.EMClientWrapper.login(EMClientWrapper.java:154)
E/MethodChannel#com.chat.im/chat_client(12501): 	at com.easemob.im_flutter_sdk.EMClientWrapper.onMethodCall(EMClientWrapper.java:64)
E/MethodChannel#com.chat.im/chat_client(12501): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#com.chat.im/chat_client(12501): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#com.chat.im/chat_client(12501): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
E/MethodChannel#com.chat.im/chat_client(12501): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/MethodChannel#com.chat.im/chat_client(12501): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#com.chat.im/chat_client(12501): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#com.chat.im/chat_client(12501): 	at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#com.chat.im/chat_client(12501): 	at android.os.Looper.loop(Looper.java:288)
```

**Comment by dujiepeng** [comment]
@ixre 没有进行初始化吧。

**Comment by ixre** [comment]
是的没有初始化
