### ISSUE TITLE
Android模拟器无问题，真机报错.

### ISSUE THREAD

**Issue by csi0n** [easemob/im_flutter_sdk#92]
模拟器上没发现问题，真机上报下面的错
报错信息
```
java.lang.NoClassDefFoundError: com.easemob.im_flutter_sdk.-$$Lambda$EMClientWrapper$1$SeaSvEeait43ywDFQFBC6P0n5MY
        at com.easemob.im_flutter_sdk.EMClientWrapper$1.onDisconnected(EMClientWrapper.java:99)
        at com.hyphenate.chat.EMClient$5.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:833)
```
是我哪边配置有问题？

**Comment by csi0n** [comment]
找到原因了。
替换：
```
import java.util.function.Consumer;//Android N（>=API 24）以上才能使用
```
为
```
import androidx.core.util.Consumer;
```
即可

**Comment by bingo** [comment]
可能是androidX支持的问题，可以搜索下之前有人提的issue，讲到怎么修改了。

**Comment by bingo** [comment]
https://github.com/easemob/im_flutter_sdk/issues/81   参考这个

**Comment by csi0n** [comment]
嗯，已经解决了，把androidx.core.util.Consumer替换成java.util.function.Consumer这个就行了。
